//
//  MovieListPresenter.swift
//  TheMovieDB
//
//  Created by Sandy Sánchez on 16/03/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MovieListPresenter {

    // MARK: - Private properties -

    private unowned let _view: MovieListViewInterface
    private let _wireframe: MovieListWireframeInterface
    private let _interactor: MovieListInteractorInterface

    // MARK: - Lifecycle -

    init(wireframe: MovieListWireframeInterface, view: MovieListViewInterface, interactor: MovieListInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }
}

// MARK: - Extensions -

extension MovieListPresenter: MovieListPresenterInterface {
    func executeGetMovieList() {
        _interactor.getMovieList { response in
            switch response {
            case .success(let result):
                self._view.successGetMovieList(response: result)
            case .failure(let error):
                self._view.failureGetMovieList(errorMessage: error.localizedDescription)
            }
        }
    }
    
    func openMovieDetail(idMovie: Int) {
        _wireframe.navigate(to: .goToDetail(idMovie: idMovie))
    }
}
