//
//  MovieListWireframe.swift
//  TheMovieDB
//
//  Created by Sandy Sánchez on 16/03/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MovieListWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard = UIStoryboard(name: "TheMovieDB", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = _storyboard.instantiateViewController(ofType: MovieListViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = MovieListInteractor()
        let presenter = MovieListPresenter(wireframe: self, view: moduleViewController, interactor: interactor)
        moduleViewController.presenter = presenter
    }
    
    func openDetail(idMovie: Int) {
        let wireframe = MovieDetailWireframe(idMovie: idMovie)
        self.navigationController?.pushWireframe(wireframe)
    }

}

// MARK: - Extensions -

extension MovieListWireframe: MovieListWireframeInterface {

    func navigate(to option: MovieListNavigationOption) {
        switch option {
        case .goToDetail(let id):
            openDetail(idMovie: id)
        }
    }
}
