//
//  MovieListInterfaces.swift
//  TheMovieDB
//
//  Created by Sandy Sánchez on 16/03/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum MovieListNavigationOption {
    case goToDetail(idMovie: Int)
}

protocol MovieListWireframeInterface: WireframeInterface {
    func navigate(to option: MovieListNavigationOption)
}

protocol MovieListViewInterface: ViewInterface {
    func successGetMovieList(response: ListResponse)
    func failureGetMovieList(errorMessage: String)
}

protocol MovieListPresenterInterface: PresenterInterface {
    func openMovieDetail(idMovie: Int)
    func executeGetMovieList()
}

protocol MovieListInteractorInterface: InteractorInterface {
    func getMovieList(completion: @escaping (Result<ListResponse, Error>) -> Void) 
}
