//
//  MovieDetailInterfaces.swift
//  TheMovieDB
//
//  Created by Sandy Sánchez on 16/03/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum MovieDetailNavigationOption {
}

protocol MovieDetailWireframeInterface: WireframeInterface {
    func navigate(to option: MovieDetailNavigationOption)
}

protocol MovieDetailViewInterface: ViewInterface {
    func successGetMovieDetail(response: MovieDetailResponse)
    func failureGetMovieDetail(errorMessage: String)
}

protocol MovieDetailPresenterInterface: PresenterInterface {
    func executeGetMovieDetail(idMovie: Int)
}

protocol MovieDetailInteractorInterface: InteractorInterface {
    func getMovieDetail(idMovie: Int, completion: @escaping (Result<MovieDetailResponse, Error>) -> Void)
}
