//
//  MovieDetailPresenter.swift
//  TheMovieDB
//
//  Created by Sandy Sánchez on 16/03/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MovieDetailPresenter {

    // MARK: - Private properties -

    private unowned let _view: MovieDetailViewInterface
    private let _wireframe: MovieDetailWireframeInterface
    private let _interactor: MovieDetailInteractorInterface

    // MARK: - Lifecycle -

    init(wireframe: MovieDetailWireframeInterface, view: MovieDetailViewInterface, interactor: MovieDetailInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }
}

// MARK: - Extensions -

extension MovieDetailPresenter: MovieDetailPresenterInterface {
    func executeGetMovieDetail(idMovie: Int) {
        self._interactor.getMovieDetail(idMovie: idMovie) { response in
            switch response {
            case .success(let result):
                self._view.successGetMovieDetail(response: result)
            case .failure(let error):
                self._view.failureGetMovieDetail(errorMessage: error.localizedDescription)
            }
        }
    }
}
